name: Playwright E2E Tests (Manual)

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Select Environment'
        type: choice
        required: true
        options:
          - UAT
          - PROD
        default: UAT
      suite:
        description: 'Select suite by tags (@regression or @smoke)'
        type: choice
        required: true
        options:
          - regression
          - smoke
        default: regression

jobs:
  e2e-tests:
    runs-on: ubuntu-latest

    env:
      ENV: ${{ inputs.environment }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: |
          npm install

      - name: Install browsers (Playwright)
        run: npx playwright install --with-deps

      - name: Run Playwright tests
        run: npx playwright test --grep @${{ inputs.suite }}

      - name: Generate Allure report
        if: always()
        run: npm run allure:generate

      - name: Upload Playwright report (HTML)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report
          if-no-files-found: ignore
          retention-days: 7

      - name: Upload Allure HTML report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: allure-report
          if-no-files-found: ignore
          retention-days: 7

      - name: Upload Allure raw results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: allure-results
          if-no-files-found: ignore
          retention-days: 7
